package fr.esgi.filesManagment.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.*;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "directories")
public class Directory {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "directories_id_seq")
    @SequenceGenerator(name = "directories_id_seq", sequenceName = "directories_id_seq", initialValue = 1, allocationSize = 1)
    private  Long id;
    private  String title;
    @OneToMany(mappedBy = "id", cascade = CascadeType.ALL)
    private Set<File> files = new HashSet<>();

}
